### ISSUE TITLE
Room codes don't work

### ISSUE THREAD

**Issue by cudzinovica** [tannerkrewson/spyfall#7] opened 2020-08-10 00:53 UTC
Someone will create a room, and tell everyone else the room code. When everyone else tries to join the room, sometimes it works but some other times they'll receive the error message "Sorry, no game was found with the access code you provided!" It seems to be random and you have a roughly 50% chance of getting the message. The code could work for one person and not work for another.

**Comment by tannerkrewson** [comment] 2020-08-10 00:57
I'm sorry this is happening! Thanks for the report. With a little bit of poking around, I was unable to reproduce this issue, but I'm also not a group of people! 😆  Does it eventually let them in if they keep trying? Does it make a difference whether your players are on Wifi or cellular data?

**Comment by cudzinovica** [comment] 2020-08-11 15:12
So I think some people did have success eventually being able to join after clicking join many times (like at least 10-20), but that was pretty rare.

 Generally we'd create a room, all but 1-3 people would be able to get in, those 1-3 people would sit there clicking join and keep getting the room doesn't exist error message, someone would create a new room, we all try to join the new room, again just a couple people can't join and we just repeat this process until finally we get lucky and everyone can join a room, took anywhere between just a couple to like 8 rooms.

I think it affected all 9 of us at some point. I personally was on WiFi and I think everyone else probably was too.

**Comment by cudzinovica** [comment] 2020-08-11 15:14
I understand this has got to be pretty annoying to debug on your own 😅. Generally my family has a weekly scheduled game night Sunday evenings. If you're interested I could let you know ahead of time the next time we'll have one.

**Comment by polm** [comment] 2020-08-21 12:42
I am also having this right now...

**Comment by tannerkrewson** [comment] 2020-08-21 22:29
thanks all. i do definitely definitely want to solve this issue... i'll try and see if i can reproduce it. thanks for the reports, if you've got any more details let me know 😄

**Comment by polm** [comment] 2020-08-22 04:47
Some room codes we used last night: peqx, kcdi, kjuz, tnbm, ewop, lbnm. Not all had problems but some did.

The person creating the room never had issues. Usually a few people would join and then it would stop working for new players (not entirely sure of that though). Even if I successfully joined a room, if someone else was unable to join, I was unable to join as a different player via an incognito window after that. 

In our group some people were unable to join more often than others, but I think everyone had issues at some point. Of the people with the most problems, one was on a phone, but the other tried multiple desktop browsers without seeing any difference.

**Comment by alenros** [comment] 2020-08-22 07:06
@tannerkrewson would it help if I wrote a selenium test?

**Comment by ktheorin1** [comment] 2020-09-02 14:32
Hi, I can confirm that this issue is unfortunately still alive and well. We all consistently get into the first game, but as soon as someone accidentally leaves and tries to join again (or we all just start a new room), the error occurs and the only thing that actually fixes it is by going to a whole new browser. It seems that the first room code a browser gets seems to glitch everything up for future room codes on that same browser. Otherwise, I'm not sure why this wouldn't happened on a different browser. Please fix this if you can- I love playing spyfall on this site!

**Comment by tannerkrewson** [comment] 2020-09-02 14:55
thanks folks. i have been able to reproduce this issue. hopefully i will get a chance to fix it soon 😄 so so so sorry this is happening 😭

**Comment by cudzinovica** [comment] 2020-09-03 18:26
Glad everyone could chime in and you were able to reproduce it. Looking forward to the fix!

**Comment by tannerkrewson** [comment] 2020-09-04 03:28
took me a while to figure out, but fixed in 9533f2a006d205f11327376960535b5ea368c808 and is live now at [spyfall.tannerkrewson.com](https://spyfall.tannerkrewson.com/)

thanks for your help everyone! enjoy

🎉 🎉

**Closed as completed by tannerkrewson** 2020-09-04 03:28 UTC

**Comment by cudzinovica** [comment] 2020-09-08 20:33
Based.

**Comment by alenros** [comment] 2020-09-08 20:34
@cudzinovica What do you mean?

**Comment by cudzinovica** [comment] 2020-09-08 22:40
I'm just saying that @tannerkrewson is based for solving this issue lol.
